name: ${project.name}
version: ${project.version}
main: ${project.groupId}.PinataKillPlugin
api-version: 1.16
description: Run custom command on pinata kill event

depend: [ PinataParty ]
softdepend: [ PlaceholderAPI ]

commands:
  pinatakill:
    aliases: [ pk ]
    description: Main plugin command.